helloworld:
  build: ./helloworld
  ports:
    - "3000"
  environment:
    SERVICE_NAME: helloworld
    SERVICE_TAGS: production

consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8500:8500"
    - "8600:53/udp"

registrator:
  command: -ip=$DOCKER_IP consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
   - consul
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

lb:
  build: ./lb
  links:
    - consul
  ports:
    - "80:80"
  environment:
    CONSUL_URL: consul:8500
    SERVICE: helloworld

